MALE_SUPERHERO_PROMPTS = {
    1: "Cyborg (DC Comics): High res, Cyberpunk-inspired hero, metallic enhancements seamlessly integrated with human form, neon-blue cybernetic lines illuminating, red cyber-eye glowing, powerful and stoic stance in a dystopian cityscape.",
    2: "Wolverine: High Res, Snarling expression, adamantium claws unsheathed, rugged iconic yellow costume.",
    3: "Superman: High Res, Stern expression, iconic cape flowing, heat-vision glowing.",
    4: "Thor: High Res, Confident demeanor, wielding Mjolnir, regal Asgardian attire.",
    5: "Captain America: High Res, Determined look, shield raised for throwing, patriotic costume.",
    6: "Hulk: High Res, Roaring angrily, massive and green, fists ready for smashing.",
    7: "Green Lantern: High Res, Heroic stance, power ring glowing, futuristic green costume.",
    8: "Aquaman: High Res, Powerful posture, trident in hand, regal Atlantean armor.",
    9: "Doctor Strange: High Res, Intensely focused, casting mystic spells, wearing magical cloak.",
    10: "Ant-Man: High Res, Human Face visible, Shrinking down, surrounded by insects, sleek costume.",
    11: "Batman: High Res, Human Face visible, Strategic pose, detective gadgets at the ready, dark and imposing suit.",
    12: "Black Panther: High Res, Human Face visible, Stealthy crouch, vibranium claws extended, sleek Wakandan suit.",
    13: "Daredevil: High Res, Human Face visible, Detailed close-up of the iconic red suit, heightened senses in action, radar sense visualization",
    14: "Ghost Rider: High Res, Fiery skull, swinging a hellfire chain, leather-clad biker.",
    15: "Green Arrow: High Res, Precise aim, master archer, clad in green costume.",
    16: "Hawkeye: High Res, Human Face visible, Sharpshooter pose, various trick arrows, sleek purple outfit.",
    17: "Hellboy: High Res, Gruff expression, supernatural investigator with filed-down horns, crimson skin.",
    18: "Incredible Hulk: High Res, Rampaging pose, unstoppable force, torn clothing.",
    19: "Iron Fist: High Res, Martial arts stance, glowing chi, martial artist attire.",
    20: "Iron Man: High Res, Inventive pose, powered armor glowing, high-tech suit.",
    21: "Spider-Man: High Res, Witty expression, mid-swing with webbing, red and blue costume.",
    22: "Dr. Manhattan: High Res, Imposing and ethereal, glowing blue figure with intricate atomic patterns, expressionless face, navigating complex moral dilemmas, adorned in a minimalist bodysuit.",
    23: "The Flash: High Res, Blazing speed captured in motion, determined expression, lightning trailing behind, iconic red and gold costume.",
    24: "Namor: High Res, Atlantean king, regal aquatic armor, trident in hand, commanding ocean waves, focused expression.",
    25: "Aquaman: High Res, Armor made of scales, trident wielded, surrounded by swirling water, determined and regal.",
    26: "Loki: High Res, Green and gold Asgardian attire, mischievous grin, conjuring illusions with scepter, dynamic pose.",
    27: "Doctor Doom: High Res, Metal armor with a flowing cape, surrounded by technological aura, imposing and calculating.",
    28: "Thanos: High Res, Purple and gold armor, wielding the Infinity Gauntlet, cosmic energy radiating, stoic and powerful.",
    29: "Joker (DC Comics): High Res, Iconic purple suit, maniacal grin, chaos in the background, unpredictable and deranged.",
    30: "Venom: High Res, Human Face visible, Symbiote suit, monstrous form with large white spider symbol, teeth bared, aggressive posture.",
    31: "Blue Beetle: High Res, Human Face visible, High-tech alien armor, glowing blue, energy weapons deployed, heroically defending.",
    32: "Deadpool: High Res, Human Face visible, Red and black costume, dual katanas in hand, irreverent and chaotic.",
    33: "Shazam: High Res, Golden and red costume, lightning bolt emblem, magical transformation in progress, heroic and awe-inspiring.",
    34: "Darkseid: High Res, Apokoliptian armor, Omega Beams firing, imposing and tyrannical, surrounded by a cosmic void.",
    35: "Moon Knight: High Res, Human Face visible, White costume with crescent emblem, moonlit night backdrop, grappling with supernatural forces.",
    36: "Magneto: High Res, Red and purple attire, manipulating metal in the air, magnetic energy radiating, intense and focused.",
    37: "Deadshot (DC Comics): High Res, Human Face visible, Tactical black and red costume, precision aiming with a wrist-mounted firearm, cold and calculating.",
    38: "Carnage: High Res, Human Face visible, Symbiote suit with chaotic tendrils, razor-sharp claws, mid-carnage, malicious and menacing.",
    39: "Black Adam: High Res, Ancient Egyptian attire, lightning-infused aura, commanding magical powers, regal and powerful."
}

FEMALE_SUPERHERO_PROMPTS = {
    1: "Hela: Human Face visible, MCU, High Res, Goddess of Death, iconic helmet, Antler-like structure, Asymmetrical design, Metallic appearance, Sleek and dark, Face-concealing, regal black and green Asgardian attire, swirling dark energy.",
    2: "Batgirl: Human Face visible, Sleek costume, cowl with bat ears, agile stance, grappling hook in hand, Gotham skyline.",
    3: "Batwoman: Human Face visible, Military-inspired suit, red bat symbol, stoic expression, utility belt, crimson hair flowing.",
    4: "Black Canary: Human Face visible, Fishnet stockings, leather jacket, Canary Cry in action, martial arts pose, urban rooftop.",
    5: "Captain Marvel: Glowing cosmic energy, star-studded suit, flying with fists ablaze, determined expression.",
    6: "Jean Grey: Telekinetic aura, iconic green and gold costume, floating in mid-air, focused expression.",
    7: "Scarlet Witch: Scarlet-red mystical aura, flowing red cloak, chaos magic in her hands, intense gaze.",
    8: "Spider-Woman: Human Face visible, Sleek spider-emblem suit, mid-air acrobatics, venom blasts, determined expression.",
    9: "Storm: Regal attire, white hair flowing, weather-controlling pose, lightning in the sky, serene expression.",
    10: "Supergirl: Iconic 'S' emblem, red cape billowing, mid-flight, powerful and confident stance.",
    11: "Wonder Woman: Amazonian armor, Lasso of Truth in hand, deflecting bullets, warrior princess pose.",
    12: "Black Widow: Tactical black suit, widow's bite gauntlets, spy pose, Natasha Romanoff's signature.",
    13: "Captain America (Sharon Carter): Captain America shield, military attire, shield throw pose, focused expression.",
    14: "Gamora: Green-skinned assassin, dual-bladed sword, combat stance, galaxy backdrop.",
    15: "Harley Quinn: Harlequin costume, oversized mallet, mischievous grin, chaotic and playful pose.",
    16: "Hawkeye (Kate Bishop): Human Face visible, Purple archer costume, bow drawn, sharpshooter pose, urban rooftop.",
    17: "Phoenix (Jean Grey): Fiery Phoenix aura, iconic green and gold costume, levitating, powerful gaze.",
    18: "Rogue: Green and yellow suit, absorbing powers, flying mid-air, determined expression.",
    19: "She-Hulk: Green skin, purple outfit, flexing muscles, lawyer attire, confident and strong pose.",
    20: "Spider-Gwen: Human Face visible, Hooded spider suit, web-swinging pose, urban backdrop, dynamic and agile.",
    21: "Valkyrie: Asgardian armor, wielding a mystical sword, fierce warrior pose, celestial background.",
    22: "Wasp (Hope van Dyne): Human Face visible, Shrinking mid-air, wings extended, red and black costume, determined expression.",
    23: "X-23: Female clone of Wolverine, mid-action pose, fierce expression, dual retractable claws extended, black and yellow combat suit with blue accents, standing in a shadowy urban alley, dramatic lighting highlighting her intense focus, hair disheveled"
}
