MALE_SUPERHERO_PROMPTS = {
    1: "Cyborg (DC Comics): High res, Cyberpunk-inspired hero, metallic enhancements seamlessly integrated with human form, neon-blue cybernetic lines illuminating, red cyber-eye glowing, powerful and stoic stance in a dystopian cityscape.",
    2: "Wolverine: High Res, Snarling expression, adamantium claws unsheathed, rugged iconic yellow costume.",
    3: "Superman: High Res, Stern expression, iconic cape flowing, heat-vision glowing.",
    4: "Thor: High Res, Confident demeanor, wielding Mjolnir, regal Asgardian attire.",
    5: "Captain America: High Res, Determined look, shield raised for throwing, patriotic costume.",
    6: "Hulk: High Res, Roaring angrily, massive and green, fists ready for smashing.",
    7: "Green Lantern: High Res, Heroic stance, power ring glowing, futuristic green costume.",
    8: "Aquaman: High Res, Powerful posture, trident in hand, regal Atlantean armor.",
    9: "Doctor Strange: High Res, Intensely focused, casting mystic spells, wearing magical cloak.",
    10: "Ant-Man: High Res, Human Face visible, Shrinking down, surrounded by insects, sleek costume.",
    11: "Batman: High Res, Human Face visible, Strategic pose, detective gadgets at the ready, dark and imposing suit.",
    12: "Black Panther: High Res, Human Face visible, Stealthy crouch, vibranium claws extended, sleek Wakandan suit.",
    13: "Daredevil: High Res, Human Face visible, Detailed close-up of the iconic red suit, heightened senses in action, radar sense visualization",
    14: "Ghost Rider: High Res, Fiery skull, swinging a hellfire chain, leather-clad biker.",
    15: "Green Arrow: High Res, Precise aim, master archer, clad in green costume.",
    16: "Hawkeye: High Res, Human Face visible, Sharpshooter pose, various trick arrows, sleek purple outfit.",
    17: "Hellboy: High Res, Gruff expression, supernatural investigator with filed-down horns, crimson skin.",
    18: "Incredible Hulk: High Res, Rampaging pose, unstoppable force, torn clothing.",
    19: "Iron Fist: High Res, Martial arts stance, glowing chi, martial artist attire.",
    20: "Iron Man: High Res, Inventive pose, powered armor glowing, high-tech suit.",
    21: "Spider-Man: High Res, Witty expression, mid-swing with webbing, red and blue costume.",
    22: "Dr. Manhattan: High Res, Imposing and ethereal, glowing blue figure with intricate atomic patterns, expressionless face, navigating complex moral dilemmas, adorned in a minimalist bodysuit.",
    23: "The Flash: High Res, Blazing speed captured in motion, determined expression, lightning trailing behind, iconic red and gold costume.",
    24: "Namor: High Res, Atlantean king, regal aquatic armor, trident in hand, commanding ocean waves, focused expression.",
    25: "Aquaman: High Res, Armor made of scales, trident wielded, surrounded by swirling water, determined and regal.",
    26: "Loki: High Res, Green and gold Asgardian attire, mischievous grin, conjuring illusions with scepter, dynamic pose.",
    27: "Doctor Doom: High Res, Metal armor with a flowing cape, surrounded by technological aura, imposing and calculating.",
    28: "Thanos: High Res, Purple and gold armor, wielding the Infinity Gauntlet, cosmic energy radiating, stoic and powerful.",
    29: "Joker (DC Comics): High Res, Iconic purple suit, maniacal grin, chaos in the background, unpredictable and deranged.",
    30: "Venom: High Res, Human Face visible, Symbiote suit, monstrous form with large white spider symbol, teeth bared, aggressive posture.",
    31: "Blue Beetle: High Res, Human Face visible, High-tech alien armor, glowing blue, energy weapons deployed, heroically defending.",
    32: "Deadpool: High Res, Human Face visible, Red and black costume, dual katanas in hand, irreverent and chaotic.",
    33: "Shazam: High Res, Golden and red costume, lightning bolt emblem, magical transformation in progress, heroic and awe-inspiring.",
    34: "Darkseid: High Res, Apokoliptian armor, Omega Beams firing, imposing and tyrannical, surrounded by a cosmic void.",
    35: "Moon Knight: High Res, Human Face visible, White costume with crescent emblem, moonlit night backdrop, grappling with supernatural forces.",
    36: "Magneto: High Res, Red and purple attire, manipulating metal in the air, magnetic energy radiating, intense and focused.",
    37: "Deadshot (DC Comics): High Res, Human Face visible, Tactical black and red costume, precision aiming with a wrist-mounted firearm, cold and calculating.",
    38: "Carnage: High Res, Human Face visible, Symbiote suit with chaotic tendrils, razor-sharp claws, mid-carnage, malicious and menacing.",
    39: "Black Adam: High Res, Ancient Egyptian attire, lightning-infused aura, commanding magical powers, regal and powerful."
}

FEMALE_SUPERHERO_PROMPTS = {
    1: "Wonderwoman high quality, 4k "
}
